apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 233e917d3d5ebc3bdd757239a2d9997fe9908692
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/rd-so-nextjs.git
  labels:
    app: e2e-nextjs
    app.kubernetes.io/instance: e2e-nextjs
    app.kubernetes.io/name: e2e-nextjs
  name: e2e-nextjs
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: e2e-nextjs
    app.kubernetes.io/instance: e2e-nextjs
    app.kubernetes.io/name: e2e-nextjs
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 233e917d3d5ebc3bdd757239a2d9997fe9908692
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/rd-so-nextjs.git
  labels:
    app: e2e-nextjs
    app.kubernetes.io/instance: e2e-nextjs
    app.kubernetes.io/name: e2e-nextjs
  name: e2e-nextjs
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: e2e-nextjs
      app.kubernetes.io/instance: e2e-nextjs
      app.kubernetes.io/name: e2e-nextjs
  template:
    metadata:
      annotations:
        app.openshift.io/runtime: js
        app.openshift.io/vcs-ref: 233e917d3d5ebc3bdd757239a2d9997fe9908692
        app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/rd-so-nextjs.git
      labels:
        app: e2e-nextjs
        app.kubernetes.io/instance: e2e-nextjs
        app.kubernetes.io/name: e2e-nextjs
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/stephan_orlowsky/rd-so-nextjs:233e917d3d5ebc3bdd757239a2d9997fe9908692
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: e2e-nextjs
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/runtime: js
    app.openshift.io/vcs-ref: 233e917d3d5ebc3bdd757239a2d9997fe9908692
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/rd-so-nextjs.git
  labels:
    app: e2e-nextjs
    app.kubernetes.io/instance: e2e-nextjs
    app.kubernetes.io/name: e2e-nextjs
  name: e2e-nextjs
spec:
  to:
    kind: Service
    name: e2e-nextjs
    weight: 100
  wildcardPolicy: None
